version: "3"

services:
  backend:
    container_name: "blog-engine-backend"
    build: .
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    env_file: ".env"
    depends_on:
      - mongoDb

  mongoDb:
    container_name: "mongoDb"
    image: "mongo"
    ports:
    - "27019:27019"

volumes:
  data_backend_libs:
    driver: local
